/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 10;
  int ASSERT = 11;
  int BOOLEAN = 12;
  int BREAK = 13;
  int BYTE = 14;
  int CASE = 15;
  int CATCH = 16;
  int CHAR = 17;
  int CLASS = 18;
  int CONTINUE = 19;
  int DO = 20;
  int DOUBLE = 21;
  int ELSE = 22;
  int EXTENDS = 23;
  int FALSE = 24;
  int FINAL = 25;
  int FINALLY = 26;
  int FLOAT = 27;
  int FOR = 28;
  int IF = 29;
  int IMPLEMENTS = 30;
  int IMPORT = 31;
  int INSTANCEOF = 32;
  int INT = 33;
  int INTERFACE = 34;
  int LONG = 35;
  int NATIVE = 36;
  int NEW = 37;
  int NULL = 38;
  int PACKAGE = 39;
  int PRIVATE = 40;
  int PROTECTED = 41;
  int PUBLIC = 42;
  int RETURN = 43;
  int SHORT = 44;
  int STATIC = 45;
  int STRICTFP = 46;
  int SUPER = 47;
  int SWITCH = 48;
  int SYNCHRONIZED = 49;
  int THIS = 50;
  int TRUE = 51;
  int THROW = 52;
  int THROWS = 53;
  int TRANSIENT = 54;
  int TRY = 55;
  int VOID = 56;
  int VOLATILE = 57;
  int WHILE = 58;
  int PLUS = 59;
  int ASSIGN = 60;
  int DEC = 61;
  int EQUAL = 62;
  int GT = 63;
  int INC = 64;
  int LAND = 65;
  int LE = 66;
  int LNOT = 67;
  int MINUS = 68;
  int PLUS_ASSIGN = 69;
  int MIN_ASSIGN = 70;
  int STAR = 71;
  int QUESTION = 72;
  int UNARY_COMPLEMENT = 73;
  int NEQ = 74;
  int DIV = 75;
  int DIV_ASSIGN = 76;
  int STAR_ASSIGN = 77;
  int REM = 78;
  int REM_ASSIGN = 79;
  int SHIFT_RIGHT = 80;
  int SHIFT_RIGHT_ASSIGN = 81;
  int USHIFT_RIGHT = 82;
  int USHIFT_RIGHT_ASSIGN = 83;
  int GTE = 84;
  int SHIFT_LEFT = 85;
  int SHIFT_LEFT_ASSIGN = 86;
  int LT = 87;
  int XOR = 88;
  int XOR_ASSIGN = 89;
  int OR = 90;
  int OR_ASSIGN = 91;
  int LOR = 92;
  int AND = 93;
  int AND_ASSIGN = 94;
  int LPAREN = 95;
  int RPAREN = 96;
  int LCURLY = 97;
  int RCURLY = 98;
  int LBRACK = 99;
  int RBRACK = 100;
  int SEMI = 101;
  int COMMA = 102;
  int DOT = 103;
  int IDENTIFIER = 104;
  int LETTER = 105;
  int DIGIT = 106;
  int NON_ZERO_DIGIT = 107;
  int DOUBLE_LITERAL = 108;
  int INT_LITERAL = 109;
  int CHAR_LITERAL = 110;
  int STRING_LITERAL = 111;
  int ESC = 112;
  int ERROR = 113;

  int DEFAULT = 0;
  int MULTI_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"continue\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"true\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"-=\"",
    "\"*\"",
    "\"?\"",
    "\"~\"",
    "\"!=\"",
    "\"/\"",
    "\"/=\"",
    "\"*=\"",
    "\"%\"",
    "\"%=\"",
    "\">>\"",
    "\">>=\"",
    "\">>>\"",
    "\">>>=\"",
    "\">=\"",
    "\"<<\"",
    "\"<<=\"",
    "\"<\"",
    "\"^\"",
    "\"^=\"",
    "\"|\"",
    "\"|=\"",
    "\"||\"",
    "\"&\"",
    "\"&=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<DOUBLE_LITERAL>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
