name: Ant
on: [push]
jobs:
  testScanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O lib/junit.jar https://repo1.maven.org/maven2/junit/junit/4.13/junit-4.13.jar
      - name: Compile .jar artifacts with ant
        run: ant testScanner

  jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Compile .jar artifacts with ant
        run: ant jar

  "individualCompileTests":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Compile .jar artifacts with ant
        run: ant jar
#      - name: SimpleOr
#        run: bin/j-- ./tests/pass/SimpleOr.java
#      - name: AssignmentOps
#        run: bin/j-- ./tests/pass/AssignmentOps.java
#      - name: Double
#        run: bin/j-- ./tests/pass/Double.java
#      - name: Colon
#        run: bin/j-- ./tests/pass/Colon.java
#      - name: MinusAssign
#        run: bin/j-- ./tests/pass/MinusAssign.java
#      - name: Prefix
#        run: bin/j-- ./tests/pass/Prefix.java

  runCompilerTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Compile .jar artifacts with ant
        run: ant jar
      - name: Run Compiler Tests (manual front-end)
        run: ant runCompilerTests

  runCompilerTestsJavaCC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Compile .jar artifacts with ant
        run: ant jar
      - name: Run Compiler Tests (automatic front-end)
        run: ant runCompilerTestsJavaCC